// EVENTUALLY THIS FILE WILL NOT BE UP ON GIT
// HAVING OUR INTERNAL KEYS USED FOR DEVELOPMENT ON GITHUB IS VERY RISKY ONCE WE GO LIVE
// SO EVENTUALLY, THIS FILE WILL BE HEAVILY RESTRICTED ACCESS AND IF YOU WANT IT, YOU'LL NEED TO GET THE UPDATED COPY EMAILED TO YOU
// THE EVENTUAL PRODUCTION SERVER WILL HAVE THESE KEYS EMBEDDED AS ENVIRONMENTAL VARIABLES

module.exports = {
  MONGO_URI:
    "mongodb+srv://BlacklightAdmin:privacysimplified@main-rq03r.mongodb.net/test?retryWrites=true&w=majority",
  HASH_KEY: "PRIVACYSIMPLIFIED"
};
